# Generated by Django 2.0 on 2023-07-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('session', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(max_length=200)),
                ('creationtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation', models.BooleanField(default=False)),
                ('updationtime', models.DateTimeField(blank=True, null=True)),
                ('completion', models.BooleanField(default=False)),
                ('completiontime', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Registartion.Register')),
            ],
        ),
    ]
