# Generated by Django 2.0 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creationtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updationtime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
