# Generated by Django 2.0 on 2023-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registartion', '0002_auto_20230715_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completiontime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creationtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deletedtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
